Repository react-native-webrtc/react-native-webrtc, pull requests merged in 2023-08, with the labels that each got.

#1426 Add pending and current descriptions
  android/src/main/java/com/oney/WebRTCModule/PeerConnectionObserver.java
  android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java
  ios/RCTWebRTC/WebRTCModule+RTCPeerConnection.m
  src/RTCPeerConnection.ts
Labels: enhancement

#1431 ios: add ability to customize RTCAudioDevice
  ios/RCTWebRTC/WebRTCModule.m
  ios/RCTWebRTC/WebRTCModuleOptions.h
  ios/RCTWebRTC/WebRTCModuleOptions.m
Labels: enhancement, ios

#1440 grammar errors and typos
  Documentation/AndroidInstallation.md
  Documentation/BasicUsage.md
  Documentation/BuildingWebRTC.md
Labels: documentation

#1442 Android, fix default transceiver direction
  android/src/main/java/com/oney/WebRTCModule/SerializeUtils.java
Labels: needs-testing, needs-reviewing

#1433 Add type to event in RTCPeerConnection and RTC DataChannel
  src/MediaStream.ts
  src/MediaStreamTrackEvent.ts
  src/MessageEvent.ts
  src/RTCDataChannel.ts
  src/RTCDataChannelEvent.ts
  src/RTCErrorEvent.ts
  src/RTCEvent.ts
  src/RTCIceCandidateEvent.ts
  src/RTCPeerConnection.ts
  src/RTCTrackEvent.ts
Labels: enhancement, needs-reviewing
