Repository react-native-webrtc/react-native-webrtc, pull requests merged in 2023-09, with the labels that each got.

#1443 Improve typing of RTCIceCandidate and MediaStream
  src/MediaStream.ts
  src/RTCIceCandidate.ts
Labels: enhancement

#1430 Add support for tvOS [local tvOS WebRTC.framework required]
  Documentation/tvOSInstallation.md
  README.md
  ios/RCTWebRTC.xcodeproj/project.pbxproj
  ios/RCTWebRTC/CaptureController.m
  ios/RCTWebRTC/ScreenCaptureController.m
  ios/RCTWebRTC/ScreenCapturePickerViewManager.m
  ios/RCTWebRTC/ScreenCapturer.m
  ios/RCTWebRTC/TrackCapturerEventsEmitter.m
  ios/RCTWebRTC/VideoCaptureController.h
  ios/RCTWebRTC/VideoCaptureController.m
  ios/RCTWebRTC/WebRTCModule+Permissions.m
  ios/RCTWebRTC/WebRTCModule+RTCMediaStream.h
  ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m
  react-native-webrtc.podspec
Labels: documentation, needs-research, needs-testing, needs-reviewing

#1447 Disable mediaStreamTrack tvOS bug fix
  ios/RCTWebRTC/WebRTCModule+RTCMediaStream.m
Labels: needs-reviewing
